export const SHOP = {
    FETCH_PRODUCTS_REQUEST: "SHOP.FETCH_PRODUCTS_REQUEST",
    GET_PRODUCTS_SUCCESS: "SHOP.GET_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAIL: "SHOP.FETCH_PRODUCTS_FAIL",
    CREATE_PRODUCT_SUCCESS: "SHOP.CREATE_PRODUCT_SUCCESS"
};

export const PRODUCT = {
    FETCH_PRODUCT_REQUEST: "PRODUCT.FETCH_PRODUCT_REQUEST",
    FETCH_PRODUCT_FAIL: "PRODUCT.FETCH_PRODUCT_FAIL",
    GET_PRODUCT_SUCCESS: "PRODUCT.GET_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_DETAIL: "PRODUCT.UPDATE_PRODUCT_DETAIL"
};
